# Generated by Django 5.0.3 on 2024-03-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(height_field='300', upload_to='Images', width_field='250')),
                ('Uploaded_by', models.CharField(max_length=200)),
                ('Craeted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
