# Generated by Django 5.0.3 on 2024-03-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='Uploaded_by',
        ),
    ]
